# Generated by Django 5.0 on 2023-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=20)),
                ('itemPrice', models.IntegerField()),
                ('itemCategory', models.CharField(max_length=15)),
            ],
        ),
    ]
